[package]
name = "rust2py"
authors = ["_fy <liuxiaochuan@novogene.com>"]
version = "0.1.0"
edition = "2018"

[lib]
name = "rust2py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "^0.11.1"
features = ["extension-module"]
